#!/bin/sh

PATH=/sbin:/usr/sbin:/bin:/usr/bin

NAME=arachned
DESC="file search engine"
DAEMON=/usr/sbin/arachned
PIDFILE=/var/run/arachne/arachned.pid
SCRIPTNAME=/etc/init.d/arachned

[ -x "$DAEMON" ] || exit 0

case "$1" in
	start)
		echo -n "Starting $DESC: "
		start-stop-daemon --start --quiet --pidfile "$PIDFILE" \
            --startas" $DAEMON"
            # Add this to enable running as the arachne user.
            # --user arachne --chuid arachne:arachne
		echo "$NAME."
		;;
	stop)
		echo -n "Stopping $DESC: "
		start-stop-daemon --stop --quiet --pidfile "$PIDFILE" \
            --retry=TERM/30/KILL/forever
            # Add this to enable running as the arachne user.
            # --user arachne
		echo "$NAME."
		;;
	*)
		echo "Usage: $SCRIPTNAME {start|stop}" >&2
		exit 1
		;;
esac

exit 0
