#!/bin/sh

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="networked file search engine"
SCRIPT=/etc/init.d/arachne

INDEXER_NAME=arachne-indexer
INDEXER_DAEMON=/usr/sbin/$INDEXER_NAME
INDEXER_PIDFILE=/var/run/arachne/indexer.pid
SEARCHER_NAME=arachne-searcher
SEARCHER_DAEMON=/usr/sbin/$SEARCHER_NAME
SEARCHER_PIDFILE=/var/run/arachne/searcher.pid

[ -x "$INDEXER_DAEMON" ] || exit 0
[ -x "$SEARCHER_DAEMON" ] || exit 0

case "$1" in
	start)
		echo -n "Starting $DESC:"
		echo -n " $INDEXER_NAME"
		start-stop-daemon --start --quiet --pidfile $INDEXER_PIDFILE  \
			--exec $INDEXER_DAEMON
		echo -n " $SEARCHER_NAME"
		start-stop-daemon --start --quiet --pidfile $SEARCHER_PIDFILE  \
			--exec $SEARCHER_DAEMON
		echo "."
		;;
	stop)
		echo -n "Stopping $DESC: "
		echo -n " $INDEXER_NAME"
		start-stop-daemon --stop --quiet --pidfile $INDEXER_PIDFILE \
			--retry=TERM/30/KILL/forever
		echo -n " $SEARCHER_NAME"
		start-stop-daemon --stop --quiet --pidfile $SEARCHER_PIDFILE \
			--retry=TERM/30/KILL/forever
		echo "."
		;;
	restart|force-reload)
		echo -n "Restarting $DESC: "
		echo -n " $INDEXER_NAME"
		start-stop-daemon --stop --quiet --pidfile $INDEXER_PIDFILE \
			--retry=TERM/30/KILL/forever
		start-stop-daemon --start --quiet --pidfile $INDEXER_PIDFILE \
			--exec $INDEXER_DAEMON
		echo -n " $SEARCHER_NAME"
		start-stop-daemon --stop --quiet --pidfile $SEARCHER_PIDFILE \
			--retry=TERM/30/KILL/forever
		start-stop-daemon --start --quiet --pidfile $SEARCHER_PIDFILE \
			--exec $SEARCHER_DAEMON
		echo "."
		;;
	*)
		echo "Usage: $SCRIPT {start|stop|restart|force-reload}" >&2
		exit 1
		;;
esac

exit 0
