#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2008 Yasser González Fernández <yglez@uh.cu>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.

"""Script to start the searcher daemon.
"""

import sys
import logging
import optparse
import ConfigParser

from aracne import __author__, __version__
from aracne.searcher import SearcherDaemon


def _parse_args():
    """Parse the command line arguments.
    """
    usage = '%prog [options]'
    version = 'aracne-searcher (Aracne) %s\nCopyright (C) 2008 %s.\nYou may' \
        ' redistribute copies of Aracne under the terms of the GNU General\n' \
        'Public License version 3 or later.  For more information about' \
        ' these matters,\nsee the file named LICENSE found in the source' \
        ' distribution.' % (__version__, ' '.join(__author__.split()[:-1]))
    description = 'Searcher daemon of the Aracne file search engine.'
    parser = optparse.OptionParser(usage=usage, version=version,
                                   description=description)
    parser.add_option('-f', '--file', metavar='FILE', dest='config_file',
                      help='specify config file (default %default)')
    parser.set_defaults(config_file='/etc/aracne/searcher.conf')
    return parser.parse_args()[0].__dict__


def _parse_config_file(config_file):
    """Parse the configuration file.
    """
    config = {
        'user': None,
        'group': None,
        'sites_file': '/etc/aracne/sites.conf',
        'pid_file': '/var/run/aracne/searcher.pid',
        'database_dir': '/var/lib/aracne/',
        'log_file': '/var/log/aracne/searcher.log',
        'log_level': logging.INFO,
    }
    parser = ConfigParser.ConfigParser()
    try:
        parser.read(config_file)
        for option in config.iterkeys():
            try:
                value = parser.get('searcher', option)
            except ConfigParser.NoOptionError:
                # Ignore missing options, use the default values.
                pass
            else:
                # Use the value from the configuration file.
                config[option] = value
    except ConfigParser.NoSectionError:
        _error('failed to read config file or searcher section is missing.')
    except ConfigParser.ParsingError:
        _error('invalid syntax in the config file.')
    except ConfigParser.Error:
        _error('an error has occurred parsing the config file.')
    else:
        if config['user'] is not None:
            try:
                config['user'] = int(config['user'])
            except ValueError:
                pass
        if config['group'] is not None:
            try:
                config['group'] = int(config['group'])
            except ValueError:
                pass
        if isinstance(config['log_level'], basestring):
            values = {
                'DEBUG': logging.DEBUG,
                'INFO': logging.INFO,
                'ERROR': logging.ERROR,
            }
            try:
                config['log_level'] = values[config['log_level'].upper()]
            except KeyError:
                _error('invalid value for log_level in the config file.')
        return config


def _parse_sites_file(sites_file):
    """Parse the file with the information of the sites.
    """
    # The format used by this file is based on the configuration file of
    # Planet <http://www.planetplanet.org/>.
    defaults = {
        'error_wait': 1800,
        'request_wait': 30,
        'min_revisit_wait': 86400,
        'max_revisit_wait': 15552000,
        'default_revisit_wait': 604800,
    }
    ConfigParser.DEFAULTSECT = 'default'
    parser = ConfigParser.ConfigParser(defaults)
    try:
        sites = []
        parser.read(sites_file)
        for section in parser.sections():
            site = {}
            site['url'] = section
            site.update(parser.items(section))
            sites.append(site)
    except ConfigParser.Error:
        _error('an error has occurred parsing the sites file.')
    else:
        if not sites:
            _error('failed to read the sites file or no sites configured.')
        else:
            int_keys = ('error_wait', 'request_wait', 'min_revisit_wait',
                        'max_revisit_wait', 'default_revisit_wait')
            for info in sites:
                for key in int_keys:
                    info[key] = int(info[key])
            return sites


def _error(message):
    """Print `message` and exit.
    """
    sys.stderr.write('Error: %s\n' % message)
    sys.exit(1)


def main():
    """Start the searcher daemon.
    """
    options = _parse_args()
    config = _parse_config_file(options['config_file'])
    sites = _parse_sites_file(config['sites_file'])
    daemon = SearcherDaemon(config, sites)
    daemon.start()
    sys.exit(0)


if __name__ == '__main__':
    main()
