#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (C) 2008 Yasser González Fernández <yglez@uh.cu>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.

import optparse

import aracne


DEFAULT_CONFIG_FILE = '/etc/aracne.conf'

DEFAULT_PID_FILE = '/var/run/aracne.pid'


def _parse_args():
    """Parse the command line arguments."""
    usage = '%prog [options]'
    version = '%%prog %s\n%s.\nThis is free software: you are free to change' \
        ' and redistribute it under the\nterms of the GNU GPL version 3 or' \
        ' later <http://www.gnu.org/licenses/gpl.html>.\nThere is NO' \
        ' WARRANTY, to the extent permitted by law.' % \
        (aracne.__version__, aracne.__copyright__)
    parser = optparse.OptionParser(usage=usage, version=version)
    parser.add_option('-c', '--config-file', metavar='FILE',
                      dest='config_file', default=DEFAULT_CONFIG_FILE,
                      help='specify configuration file (default %default)')
    parser.add_option('-p', '--pid-file', metavar='FILE',
                      dest='pid_file', default=DEFAULT_PID_FILE,
                      help='specify PID file (default %default)')
    return parser.parse_args()


def main():
    """Starts, stops or restarts the aracne daemon."""
    (options, args) = _parse_args()



if __name__ == '__main__':
    main()
