#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2008 Yasser González Fernández <yglez@uh.cu>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.

import optparse

from aracne import __version__, __copyright__
from aracne.controller import Controller


DEFAULT_CONFIG_FILE = '/etc/aracne.conf'
DEFAULT_PID_FILE = '/var/run/aracne/aracne.pid'


def _parse_args():
    """Parses the command line arguments.

    Parses the command line arguments and show information if invoked with the
    --help or --version options or an error message if an invalid option is
    specified.  Returns a dictionary mapping the names of the options to its
    values.
    """
    usage = '%prog [options]'
    version = '%%prog %s\n%s.\nThis is free software: you are free to change' \
        ' and redistribute it under the\nterms of the GNU GPL version 3 or' \
        ' later <http://www.gnu.org/licenses/gpl.html>.\nThere is NO' \
        ' WARRANTY, to the extent permitted by law.' % \
        (__version__, __copyright__)
    parser = optparse.OptionParser(usage=usage, version=version)
    parser.add_option('-c', '--configfile', metavar='FILE', dest='configfile',
                      help='specify configuration file (default %default)')
    parser.add_option('-p', '--pidfile', metavar='FILE', dest='pidfile',
                      help='specify PID file (default %default)')
    parser.set_defaults(configfile=DEFAULT_CONFIG_FILE,
                        pidfile=DEFAULT_PID_FILE)
    (options, args) = parser.parse_args()
    return options.__dict__


def _parse_configfile(configfile):
    """Parses the configuration file.
    """
    config = {
        'general' : {
            'user' : None,
            'group' : None,
        },
        'crawlmanager' : {
            'sleeptime' : 1,
        },
        'processormanager' : {
            'sleeptime' : 1,
        },
    }
    return config


def main():
    """Starts the aracne daemon.

    Entry point of the application.  This method parses the command line
    arguments and the configuration file and then creates and starts the
    `Controller`.
    """
    options = _parse_args()
    config = _parse_configfile(options['configfile'])
    config['general']['pidfile'] = options['pidfile']
    controller = Controller(config)
    controller.start()


if __name__ == '__main__':
    main()
